begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(7);
insert into profiles(id,role,display_name) values('1b000000-0000-0000-0000-000000000001','customer','Service access fixture');
set local role service_role;
select set_config('request.jwt.claim.role','service_role',true);
select lives_ok($$insert into service_zips(zip) values('28202') on conflict(zip) do update set updated_at=now()$$,'service can upsert seed coverage');
select lives_ok($$select zip from service_zips$$,'service can read configured coverage');
select lives_ok($$insert into safety_reports(id,customer_id,category,summary,guidance,hazards) values('1b000000-0000-0000-0000-000000000002','1b000000-0000-0000-0000-000000000001','plumbing','Fixture','Fixture guidance',array['leak']) on conflict(id) do update set guidance=excluded.guidance$$,'service can persist signed safety report');
select lives_ok($$select object_path from evidence_media$$,'service can resolve committed evidence metadata');
select lives_ok($$select id from provider_documents$$,'service can read private provider metadata');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.role','authenticated',true);
select throws_ok($$insert into safety_reports(id,customer_id,category,summary,guidance,hazards) values(gen_random_uuid(),'1b000000-0000-0000-0000-000000000001','plumbing','Forged','Forged',array[]::text[])$$,'42501',null,'customer cannot forge safety reports');
reset role;
set local role anon;
select throws_ok($$select zip from service_zips$$,'42501',null,'anonymous caller gains no coverage privilege');
reset role;
select * from finish();
rollback;
