/**
 * 검수된 진단 지식 레코드 모음(EN/ES). 각 레코드는 증상·후보 원인·추가 질문·
 * 안전 관찰 방법·출처를 담으며 "현장 확인 필요" 한계를 명시한다.
 */
import { bilingual as l } from './types.js';
import type { DiagnosticRecord, DiagnosticSource, LocalizedText } from './types.js';
import { sources as s } from './sources.js';
function record(id: string, category: DiagnosticRecord['category'], title: LocalizedText,
  signals: DiagnosticRecord['signals'], candidateCauses: readonly string[], question: LocalizedText,
  safeObservation: LocalizedText, sources: readonly DiagnosticSource[], redFlags: readonly string[] = []): DiagnosticRecord {
  return { id, category, title, signals, candidateCauses, questions: [question], safeObservation, sources, redFlags,
    onSiteRequired: true, limitation: 'Triage hypotheses only. Model, installation and concealed conditions need an on-site professional; media cannot prove internal component failure.' };
}
const toilet = ['toilet', 'inodoro', 'retrete'];
const faucet = ['faucet', 'tap', 'grifo', 'llave'];
const heater = ['water heater', 'hot water', 'calentador', 'agua caliente'];
const ac = ['ac', 'air conditioner', 'air conditioning', 'aire acondicionado', 'hvac'];
export const diagnosticKnowledge: readonly DiagnosticRecord[] = [
  record('under-sink-leak','plumbing',l('Water under sink','Agua debajo del fregadero'),[['sink','fregadero','lavabo'],['water','wet','leak','agua','mojado','fuga'],['under','below','cabinet','debajo','mueble']],
    ['Supply line or shutoff valve leak','Faucet hose connection leak on applicable models','Source still unconfirmed if water appears only during drainage'],l('Does it leak continuously, only using the tap, or when draining?','¿Gotea siempre, al abrir el grifo o al desaguar?'),l('Photograph the visible first wet point without touching valves, wires or fittings.','Fotografía el primer punto mojado visible sin tocar válvulas, cables ni conexiones.'),[s.underSink],['Water near outlets or disposal wiring','Rapid flooding']),
  record('ac-unusual-noise','hvac',l('Unusual AC noise','Ruido inusual del aire acondicionado'),[ac,['noise','rattl','grind','hum','buzz','ruido','zumb','golpe']],
    ['Fan mechanical problem','Compressor problem; sound alone cannot distinguish the failed part'],l('Rattle, grinding or hum; indoors or outdoors, and only during startup?','¿Traqueteo, roce o zumbido; dentro o fuera y solo al arrancar?'),l('Describe or record from a safe distance; do not remove panels or touch moving parts.','Describe o graba a distancia segura; no retires paneles ni toques piezas móviles.'),[s.acNoise],['Burning smell','Sparks','Repeated breaker trips']),
  record('dishwasher-leak','plumbing',l('Dishwasher water leak','Fuga del lavavajillas'),[['dishwasher','lavavajillas'],['leak','water','puddle','fuga','agua','charco']],
    ['Door seal or excess suds','Supply or drain hose connection','Internal pump or inlet fault requiring an appliance-qualified technician'],l('At the door or underneath, during fill, wash or drain; any excess foam?','¿En puerta o debajo, al llenar, lavar o desaguar; hay espuma excesiva?'),l('Stop use via a safely reachable normal control. Do not pull out the appliance or reach beneath it.','Detén el uso con un control normal accesible. No saques el aparato ni metas la mano debajo.'),[s.dishwasher],['Water near electrical connections','Continuing overflow']),
  record('toilet-running', 'plumbing', l('Toilet runs continuously','Inodoro con agua continua'), [toilet,['running','runs','continuous','continua','corre','corriendo','no para']],
    ['Fill valve fails to stop flow','Flush mechanism does not close'], l('Continuous noise or short refills between flushes?','¿Ruido continuo o recargas breves entre descargas?'), l('Describe when the sound starts; record from a dry safe position.','Describe cuándo comienza; graba desde un lugar seco y seguro.'), [s.toilet]),
  record('toilet-cycling', 'plumbing', l('Toilet refills intermittently','Inodoro se recarga solo'), [toilet,['intermittent','occasionally','refill','recarga','solo','every']],
    ['Slow tank-to-bowl leak','Refill hose siphoning in applicable models'], l('Does it refill without anyone flushing?','¿Se recarga sin que nadie lo descargue?'), l('Note the refill interval without dismantling parts.','Anota el intervalo sin desmontar piezas.'), [s.toiletCycle,s.toilet]),
  record('toilet-external-leak', 'plumbing', l('Water outside toilet','Agua fuera del inodoro'), [toilet,['leak','water','fuga','agua','pierde']],
    ['Supply connection leak','Tank-to-bowl connection leak','Source around base not yet established'], l('Where does water first appear: supply, tank joint, or floor?','¿Dónde aparece primero: suministro, unión del tanque o suelo?'), l('Photograph visible water from dry ground; identify toilet model.','Fotografía el agua desde suelo seco e identifica el modelo.'), [s.toiletLeak], ['Sewage overflow','Water near electricity']),
  record('faucet-base-leak','plumbing',l('Faucet base leak','Fuga en la base del grifo'),[faucet,['leak','drip','fuga','gotea','agua']],
    ['Spout seal wear on applicable models','Pullout hose seal or vacuum breaker issue'],l('Is water at the base or coming from the outlet when off?','¿Sale por la base o por la salida estando cerrado?'),l('Send model and a photo of the first wet area.','Envía modelo y foto del primer punto mojado.'),[s.faucet]),
  record('faucet-low-flow','plumbing',l('Weak faucet flow','Poco caudal del grifo'),[faucet,['low','weak','pressure','flow','poca','poco','presion','caudal']],
    ['Aerator or spray screen obstruction','Diverter restriction on applicable models'],l('Both hot and cold, and does the spray behave differently?','¿Ocurre con fría y caliente? ¿El rociador funciona distinto?'),l('Compare another tap without removing plumbing.','Compara otro grifo sin desmontar tuberías.'),[s.flow]),
  record('shower-drip','plumbing',l('Shower drips when off','Ducha gotea cerrada'),[['shower','ducha'],['drip','leak','gotea','fuga']],
    ['Cartridge sealing fault in compatible Moen valves'],l('Does dripping continue long after shutting off?','¿Sigue goteando mucho después de cerrarla?'),l('Record valve model and duration; do not open the wall.','Anota modelo y duración; no abras la pared.'),[s.shower]),
  record('drain-backup','plumbing',l('Drain backup','Retorno del desagüe'),[['drain','sewer','sink','desague','alcantarillado','fregadero'],['clog','slow','backup','blocked','atascado','lento','rebosa','regresa']],
    ['Private drain obstruction','Public sewer obstruction possible if backup persists'],l('One fixture or several, and is wastewater still rising without water use?','¿Uno o varios aparatos? ¿Sube sin usar agua?'),l('Avoid sewage contact; report ongoing overflow to Charlotte Water 311 or 704-336-7600.','Evita contacto; reporta desbordamiento continuo al 311 o 704-336-7600.'),[s.water],['Sewage entering occupied space']),
  record('building-water-leak','plumbing',l('Building water leak','Fuga de agua del edificio'),[['pipe','ceiling','wall','tuberia','techo','pared'],['leak','wet','water','fuga','mojado','agua']],
    ['Private plumbing leak; origin not established'],l('Does wetness track rain or use of a fixture above?','¿Coincide con lluvia o uso de un aparato arriba?'),l('Keep away from sagging surfaces and wet electrical equipment.','Aléjate de superficies hundidas y equipos eléctricos mojados.'),[s.water],['Sagging ceiling','Electrical contact','Rapid flooding']),
  record('heater-no-hot-water','plumbing',l('Insufficient hot water','Falta agua caliente'),[heater,['no','not','cold','less','insufficient','fria','poca','falta']],
    ['Demand exceeds recovery','Heating component or thermostat fault','Sediment reduces capacity'],l('All taps or only one, and what heater type?','¿Todos los grifos o uno? ¿Qué tipo de calentador?'),l('Read exterior display only.','Lee solo la pantalla exterior.'),[s.heater]),
  record('heater-leak','plumbing',l('Water near heater','Agua junto al calentador'),[heater,['leak','pool','fuga','charco','gotea']],
    ['Fitting or relief valve leak','Condensation','Tank corrosion'],l('Water from a fitting, drain pipe, or tank body?','¿Sale de conexión, descarga o tanque?'),l('Do not touch hot discharge.','No toques la descarga caliente.'),[s.heater],['Hot discharge','Electrical contact']),
  record('heater-discolored','plumbing',l('Discolored hot water','Agua caliente descolorida'),[heater,['rust','brown','discolor','oxide','marron','oxido','color']],
    ['Tank corrosion or anode deterioration'],l('Is cold water also affected?','¿Afecta también al agua fría?'),l('Photograph color without tasting water.','Fotografía el color sin probar el agua.'),[s.heater]),
  record('heater-noise','plumbing',l('Heater unusual noise','Ruido del calentador'),[heater,['noise','rumbl','popping','bang','ruido','golpe','vibra']],
    ['Sediment or scale','Heat-pump airflow or component problem'],l('Tank, tankless or heat pump; when does noise occur?','¿Tanque, instantáneo o bomba de calor? ¿Cuándo suena?'),l('Record from outside the cabinet.','Graba desde fuera de la carcasa.'),[s.heatPump],['Burning smell','Repeated breaker trips']),
  record('ac-no-cooling','hvac',l('AC does not cool','Aire no enfría'),[ac,['not cool','no cool','warm','no enfria','caliente','not working']],
    ['Thermostat setting','Restricted airflow','Refrigerant or outdoor-unit fault'],l('Is air weak, warm, or absent?','¿El aire es débil, caliente o no sale?'),l('Share thermostat display and visible ice; do not open panels.','Comparte pantalla y hielo visible; no abras paneles.'),[s.ac],['Burning smell','Repeated breaker trips']),
  record('ac-ice','hvac',l('Ice on AC','Hielo en el aire acondicionado'),[ac,['ice','frozen','frost','hielo','congel']],
    ['Restricted airflow','Low refrigerant'],l('Visible ice and reduced airflow together?','¿Hielo visible y menor caudal juntos?'),l('Stop cooling using a safely reachable normal control; no refrigerant work.','Detén refrigeración con control normal accesible; no manipules refrigerante.'),[s.ac]),
  record('ac-water-leak','hvac',l('AC water leak','Aire acondicionado gotea'),[ac,['leak','water','drip','fuga','agua','gotea']],
    ['Condensate drain blockage','Damaged drain pan','Melting coil ice'],l('Indoor or outdoor water; during cooling or after stopping?','¿Agua dentro o fuera; durante uso o al parar?'),l('Avoid wet electrics; photograph location from a dry area.','Evita electricidad mojada; fotografía desde zona seca.'),[s.acLeak],['Water near electrical equipment','Ceiling damage']),
  record('window-condensation','handyman',l('Window condensation','Condensación en ventana'),[['window','glass','ventana','vidrio'],['condensation','fog','condensacion','empana']],
    ['Indoor moisture condensing on cold glass; not proof of seal failure'],l('On room-side glass or trapped between panes?','¿En cara interior o entre cristales?'),l('Describe side and weather; no climbing.','Describe lado y clima; no subas a alturas.'),[s.window]),
  record('window-water','handyman',l('Window sill water','Agua en alféizar'),[['window','door','ventana','puerta'],['water','rain','leak','agua','lluvia','fuga']],
    ['Drainage restriction in applicable window or door design','Water entry source requires inspection'],l('Only during rain, and does pooling drain away?','¿Solo con lluvia? ¿Se evacua el agua acumulada?'),l('Photograph reachable sill from inside.','Fotografía alféizar accesible desde dentro.'),[s.drainage]),
  record('wall-cracks','handyman',l('Wall cracks or movement','Grietas o movimiento'),[['wall','brick','foundation','pared','ladrillo','cimiento'],['crack','gap','lean','grieta','separa','inclina']],
    ['Building movement or existing damage; structural status unknown'],l('New or widening, with roof sagging or gaps around doors?','¿Nuevas o crecen, con techo hundido o huecos en puertas?'),l('Photograph from a safe position; structural assessment needs an expert.','Fotografía desde lugar seguro; requiere evaluación experta.'),[s.structure],['Rapid movement','Leaning wall','Sagging roof']),
  record('co-alarm-or-symptoms','emergency',l('Carbon monoxide alarm or symptoms','Alarma o síntomas de monóxido de carbono'),[
    ['carbon monoxide','co alarm','co detector','furnace','fuel-burning','monoxido de carbono','alarma de co','detector de co','horno','combustion'],
    ['carbon monoxide','co alarm','co detector','headache','dizzy','nausea','confusion','monoxido de carbono','alarma de co','detector de co','dolor de cabeza','mareo','nausea','confusion']],
    ['A carbon monoxide source may be present; symptoms and an alarm cannot identify the appliance remotely / Puede haber una fuente de monóxido; los síntomas y una alarma no identifican el aparato a distancia','An alarm malfunction is possible, but must not be assumed / Es posible una falla de la alarma, pero no debe suponerse'],
    l('Is a CO alarm sounding, or does anyone have headache, dizziness, nausea, weakness, chest pain, or confusion?','¿Suena una alarma de CO o alguien tiene dolor de cabeza, mareo, náusea, debilidad, dolor de pecho o confusión?'),
    l('Everyone must move to fresh air now; from outside call 911. Do not re-enter until responders clear it.','Todos deben salir ahora al aire libre; desde afuera llama al 911. No vuelvan hasta que los servicios de emergencia lo autoricen.'),
    [s.epaCarbonMonoxide,s.cdcCarbonMonoxide,s.cpscCarbonMonoxide],
    ['CO alarm sounding / Alarma de CO activa','Headache, dizziness, nausea, weakness, chest pain, or confusion / Dolor de cabeza, mareo, náusea, debilidad, dolor de pecho o confusión']),
  record('sewage-backup','emergency',l('Sewage or contaminated-water backup','Retorno de aguas residuales o contaminadas'),[
    ['sewage','wastewater','sewer water','raw sewer','aguas residuales','agua de alcantarillado','heces'],
    ['backup','backing up','overflow','rising','respaldo','retorno','rebosa','sube']],
    ['A private drain or sewer-lateral obstruction may be involved / Puede haber una obstrucción del desagüe privado o ramal de alcantarillado','A public sewer problem is possible when multiple drains are affected / Es posible un problema público si afecta varios desagües'],
    l('Is contaminated water rising from one fixture or from several drains even when no water is being used?','¿El agua contaminada sube por un aparato o por varios desagües aunque no se use agua?'),
    l('Keep people and pets away and avoid all contact; request professional contaminated-water cleanup and report an active sewer overflow to Charlotte Water at 311 or 704-336-7600.','Mantén alejadas a personas y mascotas y evita todo contacto; solicita limpieza profesional de agua contaminada y reporta un desbordamiento activo a Charlotte Water al 311 o 704-336-7600.'),
    [s.water,s.epaFloodCleanup],
    ['Sewage entering occupied space / Aguas residuales entrando al área ocupada','Rapidly rising contaminated water / Agua contaminada subiendo rápidamente','Contaminated water touching electrical equipment / Agua contaminada en contacto con equipo eléctrico']),
  record('post-leak-mold-moisture','handyman',l('Mold or lingering moisture after a leak','Moho o humedad persistente después de una fuga'),[
    ['leak','flood','water damage','wet','fuga','inundacion','daño por agua','mojado','humedad'],
    ['mold','musty','damp','still wet','moho','olor a humedad','humedo','sigue mojado']],
    ['Materials may still be retaining moisture after the water source stopped / Los materiales pueden retener humedad después de parar la fuente','Visible or suspected mold growth is possible, but type and extent cannot be identified remotely / Puede haber crecimiento de moho, pero no se puede identificar el tipo ni el alcance a distancia'],
    l('Has the material stayed wet for more than 24–48 hours, and is the affected area larger than about 10 square feet or linked to sewage or HVAC?','¿El material lleva mojado más de 24–48 horas y el área supera unos 10 pies cuadrados o está relacionada con aguas residuales o HVAC?'),
    l('From a dry area, photograph the visible boundary and note the moisture source and duration; do not disturb mold or contaminated material.','Desde una zona seca, fotografía el límite visible y anota la fuente y duración; no alteres moho ni material contaminado.'),
    [s.epaMoldCleanup,s.epaFloodCleanup,s.cdcMoldCleanup],
    ['Sewage or contaminated-water source / Fuente de aguas residuales o agua contaminada','Water touching electrical equipment / Agua en contacto con equipo eléctrico','More than about 10 square feet, HVAC contamination, or a high-risk occupant / Más de unos 10 pies cuadrados, contaminación de HVAC o un ocupante de alto riesgo']),
  record('furnace-combustion-warning','emergency',l('Furnace combustion warning signs','Señales de advertencia de combustión del horno'),[
    ['furnace','boiler','gas heater','horno','caldera','calentador de gas'],
    ['yellow flame','soot','puff','boom','exhaust','flue smell','llama amarilla','hollin','explosion','olor a escape','gases de combustion']],
    ['Inadequate combustion air or a venting problem may be involved / Puede haber aire de combustión insuficiente o un problema de ventilación','An ignition, burner, or heat-exchanger problem is possible; the component cannot be identified remotely / Puede haber un problema de encendido, quemador o intercambiador; no se puede identificar el componente a distancia'],
    l('Is there a yellow or wavering flame, soot, a boom at ignition, exhaust odor, a CO alarm, or anyone feeling ill?','¿Hay llama amarilla o inestable, hollín, explosión al encender, olor a escape, alarma de CO o alguien se siente mal?'),
    l('Stop the system with a normal control only if safely reachable, leave the area, and arrange urgent qualified service; for a CO alarm or symptoms, go outside and call 911.','Detén el sistema solo con un control normal si es seguro alcanzarlo, sal del área y solicita servicio calificado urgente; con alarma de CO o síntomas, sal y llama al 911.'),
    [s.epaCarbonMonoxide,s.cdcCarbonMonoxide,s.energyStarHvacMaintenance,s.mecklenburgCodeSupport],
    ['CO alarm or illness / Alarma de CO o malestar','Gas odor / Olor a gas','Soot, flame rollout, exhaust indoors, or delayed-ignition boom / Hollín, llama fuera del quemador, escape interior o explosión de encendido']),
  record('hvac-repeated-breaker','emergency',l('Repeated HVAC breaker trip or electrical warning','Disparo repetido del interruptor o advertencia eléctrica de HVAC'),[
    ['ac','air conditioner','hvac','heat pump','furnace','aire acondicionado','bomba de calor','horno'],
    ['breaker','trip','spark','burning smell','electrical','interruptor','disyuntor','se dispara','chispa','olor a quemado','electrico']],
    ['An HVAC supply, disconnect, or wiring fault is possible / Puede haber una falla en la alimentación, desconexión o cableado de HVAC','A motor, capacitor, compressor, or other equipment fault is possible; the energized fault cannot be isolated remotely / Puede haber una falla de motor, capacitor, compresor u otro equipo; no puede aislarse a distancia'],
    l('Has the breaker tripped more than once, or is there a burning odor, buzzing, heat, smoke, or sparking?','¿El interruptor se disparó más de una vez o hay olor a quemado, zumbido, calor, humo o chispas?'),
    l('Do not reset it again or open equipment or the electrical panel; keep away and contact a qualified HVAC or electrical professional. Call 911 for smoke or fire.','No lo restablezcas otra vez ni abras el equipo o panel eléctrico; aléjate y contacta a un profesional calificado de HVAC o electricidad. Llama al 911 si hay humo o fuego.'),
    [s.energyStarHvacMaintenance,s.doeAcMaintenance,s.mecklenburgPermitting,s.mecklenburgTradePermitting],
    ['Repeated breaker trips / Disparos repetidos','Burning odor, hot panel, smoke, or sparks / Olor a quemado, panel caliente, humo o chispas','Water at electrical equipment / Agua en equipo eléctrico']),
  record('heat-pump-frost-aux','hvac',l('Heat-pump frost or prolonged auxiliary heat','Escarcha o calor auxiliar prolongado de bomba de calor'),[
    ['heat pump','bomba de calor'],
    ['frost','ice','aux heat','auxiliary heat','emergency heat','defrost','escarcha','hielo','calor auxiliar','calor de emergencia','descongelacion']],
    ['A thin temporary frost layer during a defrost cycle can be normal and is not proof of failure / Una capa fina y temporal durante el deshielo puede ser normal y no prueba una falla','Persistent heavy ice, restricted airflow, controls, outdoor-unit, or refrigerant-circuit problems are possible / El hielo persistente, flujo restringido o problemas de controles, unidad exterior o refrigerante son posibles'],
    l('Does thin frost clear during defrost, or does heavy ice persist while the home misses setpoint or auxiliary heat stays on?','¿La escarcha fina desaparece al descongelar o persiste hielo grueso mientras no alcanza la temperatura o sigue el calor auxiliar?'),
    l('Observe the thermostat and outdoor unit from a safe clear path; do not chip ice, remove panels, or touch the refrigerant circuit.','Observa el termostato y la unidad exterior desde un camino seguro; no rompas hielo, retires paneles ni toques el circuito de refrigerante.'),
    [s.energyStarHvacMaintenance,s.doeAcMaintenance,s.epaSection608,s.mecklenburgPermitting],
    ['Burning smell, sparks, or repeated breaker trips / Olor a quemado, chispas o disparos repetidos','Outdoor unit blocked by unsafe ice or overhead falling ice / Unidad exterior bloqueada por hielo peligroso o caída de hielo']),
  record('gas-emergency','emergency',l('Suspected gas leak','Posible fuga de gas'),[['gas smell','smell gas','gas leak','rotten egg','olor a gas','fuga de gas','huevo podrido']],
    ['Possible gas release; remote confirmation unsafe'],l('Are you safely away from the area?','¿Ya estás lejos y a salvo?'),l('Leave immediately. From a safe location call 911 or Piedmont 800-752-7504. Do not return until cleared.','Sal de inmediato. Desde lugar seguro llama 911 o Piedmont 800-752-7504. No vuelvas sin autorización.'),[s.gas],['Gas odor','Gas alarm','Hissing near gas equipment']),
  // ---------- electrical ----------
  record('dead-outlet','electrical',l('Outlet not working','Enchufe sin corriente'),[
    ['outlet','receptacle','socket','plug','enchufe','tomacorriente'],
    ['dead','not working','no power','stopped','no funciona','sin corriente','no tiene']],
    ['Upstream GFCI outlet tripped','Tripped breaker','Loose or failed wiring at the outlet'],l('Do other outlets or lights nearby work, and is there a GFCI outlet with a reset button in the room, bathroom, garage, or kitchen?','¿Funcionan otros enchufes o luces cercanos y hay un enchufe GFCI con botón de reinicio en el cuarto, baño, garaje o cocina?'),l('If a GFCI reset button is safely reachable you may press it once; do not remove the cover plate or touch wiring.','Si hay un botón de reinicio GFCI accesible puedes pulsarlo una vez; no retires la tapa ni toques el cableado.'),[s.nfpaElectrical,s.mecklenburgTradePermitting],['Burning smell','Warm or discolored faceplate','Sparks or buzzing']),
  record('breaker-trips','electrical',l('Breaker keeps tripping','Interruptor se dispara'),[
    ['breaker','circuit','interruptor','disyuntor'],
    ['trip','tripping','keeps','turns off','se dispara','salta','apaga']],
    ['Overloaded circuit','Short or ground fault on that circuit','Failing breaker or connection'],l('Which breaker is it, and what was running when it tripped — did it start after plugging in something new?','¿Qué interruptor es y qué estaba funcionando al dispararse — comenzó tras conectar algo nuevo?'),l('Do not reset it repeatedly or open the panel; unplug recent loads and note which breaker trips.','No lo restablezcas repetidamente ni abras el panel; desconecta cargas recientes y anota qué interruptor salta.'),[s.nfpaElectrical,s.mecklenburgTradePermitting],['Trips instantly on reset','Burning smell or hot panel','Buzzing from the panel']),
  record('flickering-lights','electrical',l('Lights flickering or dimming','Luces parpadean'),[
    ['light','lights','luz','luces'],
    ['flicker','flickering','dim','dimming','blink','parpadea','titila','apaga']],
    ['Loose bulb or fixture connection','Circuit connection problem','Utility-side voltage issue if the whole home is affected'],l('One fixture or several rooms — and does it happen when a big appliance kicks on?','¿Una lámpara o varios cuartos — y ocurre cuando arranca un aparato grande?'),l('Note which rooms and when it happens; do not open fixtures or the panel.','Anota qué cuartos y cuándo ocurre; no abras lámparas ni el panel.'),[s.nfpaElectrical],['Whole-house flicker with burning smell','Flicker plus buzzing at the panel']),
  record('electrical-warning','emergency',l('Electrical emergency signs','Señales eléctricas de emergencia'),[
    ['outlet','panel','wiring','wire','electrical','enchufe','cable','electrico','disyuntor'],
    ['spark','sparks','smoke','burning smell','sizzle','buzz','hot','melting','chispa','humo','olor a quemado','zumbido','caliente','derritiendo']],
    ['An energized fault may be present; it cannot be isolated remotely / Puede haber una falla energizada; no se puede aislar a distancia'],
    l('Is there sparking, smoke, a burning odor, buzzing, or a hot or discolored panel or outlet?','¿Hay chispas, humo, olor a quemado, zumbido o un panel o enchufe caliente o descolorido?'),
    l('Keep everyone away and do not touch the outlet, panel, or wiring; call 911 for smoke or fire. For ongoing arcing, an electrician or the utility emergency line is required.','Aléjate y no toques el enchufe, panel ni cableado; llama al 911 si hay humo o fuego. Con arco continuo se requiere electricista o la línea de emergencia de la compañía eléctrica.'),
    [s.nfpaElectrical,s.mecklenburgTradePermitting],
    ['Smoke or visible fire / Humo o fuego visible','Sparking or arcing / Chispas o arco','Hot, buzzing, or discolored panel / Panel caliente, zumbando o descolorido']),
  // ---------- painting ----------
  record('interior-repaint','painting',l('Interior repaint','Pintura interior'),[
    ['paint','repaint','pintar','pintura'],
    ['room','wall','ceiling','bedroom','living','kitchen','interior','cuarto','pared','techo','cocina','sala']],
    ['Standard repaint over sound surfaces','Prep-heavy job if patching, sanding, or stain blocking is needed'],l('How many rooms or walls, roughly what size, and is there peeling, stains, holes, or texture to deal with first?','¿Cuántos cuartos o paredes, de qué tamaño aproximado, y hay pintura descascarada, manchas, agujeros o textura previa?'),l('Photograph each wall and any damage spots; note current colors and the new color if chosen.','Fotografía cada pared y las zonas dañadas; anota colores actuales y el nuevo color si lo elegiste.'),[s.epaLeadRrp],['Home built before 1978 — possible lead paint','Large water stains or active moisture']),
  record('peeling-paint','painting',l('Paint peeling or bubbling','Pintura descascarada o con burbujas'),[
    ['paint','pintura'],
    ['peel','peeling','bubbl','flaking','chipping','descascar','burbuja','desconcha','agrieta']],
    ['Moisture behind the wall is pushing the paint off','Poor surface prep or adhesion failure','Normal aging on a high-moisture room'],l('Is the peeling near a bathroom, kitchen, exterior wall, or anywhere water could get in — and roughly how old is the paint?','¿La descamación está cerca de baño, cocina, pared exterior o donde pueda entrar agua — y qué edad tiene la pintura?'),l('Photograph the affected area and the widest edge; do not scrape or sand — homes built before 1978 may have lead paint underneath.','Fotografía la zona afectada y el borde más ancho; no rasques ni lijes — casas anteriores a 1978 pueden tener pintura con plomo debajo.'),[s.epaLeadRrp],['Pre-1978 home — lead paint risk','Active moisture or mold behind the paint']),
  record('exterior-painting','painting',l('Exterior repaint','Pintura exterior'),[
    ['paint','repaint','pintar','pintura'],
    ['outside','exterior','siding','trim','porch','deck','front','outside wall','exterior','fachada','revestimiento','porche']],
    ['Weathered coating needing standard prep and repaint','Peeling or wood rot increasing prep scope','Pre-1978 home may require lead-safe certified work'],l('What surface — siding, brick, wood trim — how many stories, and is there peeling or rotted wood?','¿Qué superficie — revestimiento, ladrillo, madera — cuántos pisos, y hay pintura levantada o madera podrida?'),l('Photograph all sides plus close-ups of peeling or damaged spots; note the year the home was built if known.','Fotografía todos los lados y acercamientos de zonas dañadas; anota el año de construcción si lo sabes.'),[s.epaLeadRrp],['Pre-1978 home — lead-safe certified renovator required','Rotted wood needing carpentry before paint','Work above one story']),
  // ---------- pest_control ----------
  record('ants-indoors','pest_control',l('Ants indoors','Hormigas en casa'),[
    ['ant','ants','hormiga','hormigas'],
    ['inside','kitchen','counter','trail','crawl','inside','cocina','fila','camino']],
    ['Foragers entering for food or moisture','Nest inside a wall or under the slab','Colony outside sending trails in'],l('Where do they appear — kitchen, bathroom, windows — do you see a trail, and roughly how many a day?','¿Dónde aparecen — cocina, baño, ventanas — ves una fila, y aproximadamente cuántas al día?'),l('Photograph a few close-up and the entry path; keep kids and pets away from bait stations.','Fotografía algunas de cerca y el camino de entrada; mantén lejos de niños y mascotas los cebos.'),[s.npmaPestGuide],['Carpenter ant frass or wood damage','Swarmers indoors']),
  record('roaches','pest_control',l('Cockroaches','Cucarachas'),[
    ['roach','roaches','cockroach','cucaracha','cucarachas'],
    ['kitchen','bathroom','sink','night','inside','cocina','baño','noche']],
    ['German cockroach infestation in kitchen or bath','American roach entering from drains or outside','Recent introduction via boxes, bags, or appliances'],l('When do you see them — at night or in daylight — how many, and are they small and tan or large and reddish?','¿Cuándo las ves — de noche o de día — cuántas, y son pequeñas y claras o grandes y rojizas?'),l('Photograph one for identification plus where you see them; empty standing water and grease before the visit.','Fotografía una para identificarla y dónde aparecen; retira agua estancada y grasa antes de la visita.'),[s.npmaPestGuide],['Daytime sightings suggest a heavy infestation','Droppings or egg cases near food areas']),
  record('rodent-signs','pest_control',l('Rodent signs','Señales de roedores'),[
    ['mouse','mice','rat','rodent','droppings','scratching','gnaw','raton','rata','roedor','excremento','rasguño'],
    ['wall','attic','kitchen','garage','cabinet','hear','noise','droppings','pared','atico','cocina','garaje','ruido','excremento']],
    ['Mice or rats entering through a small gap','Nest established in attic, wall, or garage','Past activity without current infestation'],l('Where do you hear or see signs — attic, walls, kitchen, garage — and are there droppings or gnaw marks?','¿Dónde oyes o ves señales — ático, paredes, cocina, garaje — y hay excrementos o marcas de roído?'),l('Photograph droppings and any entry gaps; do not sweep or vacuum droppings — ventilate and leave cleanup guidance to the technician.','Fotografía excrementos y huecos de entrada; no barras ni aspires excrementos — ventila y deja la limpieza al técnico.'),[s.cdcRodents,s.npmaPestGuide],['Droppings near food preparation areas','Scratching inside occupied rooms at night']),
  record('termites','pest_control',l('Possible termites','Posibles termitas'),[
    ['termite','termites','mud tube','swarmer','winged','termita','termitas','tubo de barro','enjambre','alada'],
    ['foundation','wood','beam','wall','floor','crawl','cimiento','madera','viga','suelo']],
    ['Subterranean termite colony — common in the Charlotte area','Carpenter ants or old inactive damage','Swarmers blown in from a nearby colony'],l('Do you see pencil-thin mud tubes on the foundation, swarmers or shed wings indoors, or wood that sounds hollow when tapped?','¿Ves tubos de barro del grosor de un lápiz en el cimiento, enjambre o alas sueltas dentro, o madera que suena hueca al golpearla?'),l('Photograph the tubes, wings, or damaged wood from where you stand; do not break tubes or pull apart the wood.','Fotografía los tubos, alas o madera dañada desde donde estás; no rompas los tubos ni arranques la madera.'),[s.epaTermites,s.npmaPestGuide],['Active swarm indoors','Soft or sagging structural wood']),
  record('wasp-nest','pest_control',l('Wasps or hornets','Avispas o avispón'),[
    ['wasp','wasps','hornet','yellow jacket','bee','bees','nest','sting','avispa','avispas','abeja','abejas','nido','picadura'],
    ['eave','roof','ground','wall','porch','attic','tree','alero','techo','suelo','pared','porche','atico','arbol']],
    ['Paper wasp or hornet nest under eaves','Yellow jacket nest in the ground or a wall void','Honey bee colony — needs relocation, not spraying'],l('Where is the nest or activity — eaves, ground, inside a wall — how big, and is anyone in the home allergic to stings?','¿Dónde está el nido o la actividad — alero, suelo, dentro de una pared — qué tamaño, y alguien en casa es alérgico a picaduras?'),l('Photograph from a distance and keep people and pets away; do not spray, seal, or knock down the nest yourself.','Fotografía a distancia y mantén lejos a personas y mascotas; no rocíes, selles ni derribes el nido.'),[s.npmaPestGuide],['Anyone allergic to stings','Activity inside living spaces']),
];
