/**
 * 지식 레코드가 참조하는 제조사/공식 문서 출처 목록과 접근일.
 */
import { source } from './types.js';
const researchedSource = (title: string, url: string) => ({ ...source(title, url), accessedAt: '2026-09-06' });
export const sources = {
  underSink: source('Moen: Kitchen Faucet Leaking Under The Sink Base', 'https://solutions.moen.com/Article_Library/Kitchen_Faucet%3A_Leaking_Under_The_Sink_Base'),
  acNoise: source('Carrier: Air Conditioner Repair Guide', 'https://www.carrier.com/us/en/residential/hvac-resources/air-conditioners/ac-repair/'),
  dishwasher: source('Whirlpool: Dishwasher Leaking Troubleshooting Guide', 'https://producthelp.whirlpool.com/Dishwashers/Product_Info/Dishwasher_Product_Assistance/Dishwasher_Leaking_Troubleshooting_Guide'),
  toilet: source('Kohler: Toilet Constantly Leaking or Running', 'https://assist.kohler.com/en/toilets-and-seats/Toilet-Constantly-Leaking-or-Running'),
  toiletLeak: source('Kohler: Pressure Assist troubleshooting', 'https://resources.kohler.com/webassets/kpna/catalog/pdf/en/1196261_17.pdf'),
  toiletCycle: source('Kohler: Tank Leak - Fill Valve Hose Position', 'https://assist.kohler.com/en/toilets-and-seats/Tank-Leak-Fill-Valve-Hose-Position'),
  faucet: source('Moen: Kitchen faucet leaks at the bottom of the spout', 'https://solutions.moen.com/FAQ%27s/FAQ%27s-Troubleshooting/Kitchen/Kitchen_faucet_leaks_at_the_bottom_of_the_spout'),
  flow: source('Moen: Kitchen Faucet Low Flow', 'https://solutions.moen.com/Article_Library/Kitchen_Faucet%3A_Low_Flow'),
  shower: source('Moen: INS2151C troubleshooting', 'https://www.moen.com/shared/docs/instruction-sheets/ins2151c.pdf'),
  water: source('Charlotte Water: Fixes & Troubleshooting', 'https://www.charlottenc.gov/water/Customer-Care/Fixes-Troubleshooting'),
  heater: source('Rheem: 5 Signs Your Water Heater Is Going Bad', 'https://www.rheem.com/water-heating/articles/5-signs-your-water-heater-is-going-bad-and-what-to-do-about-it/'),
  heatPump: source('Rheem: Heat Pump Water Heater Maintenance', 'https://www.rheem.com/water-heating/articles/heat-pump-water-heater-maintenance-complete-rheem-care-guide-troubleshooting/'),
  ac: source('Carrier: Troubleshoot an Air Conditioner', 'https://www.carrier.com/us/en/residential/hvac-resources/air-conditioners/troubleshoot-an-ac-not-working/'),
  acLeak: source('Carrier: Why Is My AC Leaking Water?', 'https://www.carrier.com/us/en/residential/hvac-resources/air-conditioners/why-is-my-ac-leaking-water/'),
  window: source('Andersen: Interior Glass Condensation', 'https://helpcenter.andersenwindows.com/aw/articles/Knowledge/Condensation-on-the-Interior-of-Window-or-Patio-Door-Glass'),
  drainage: source('Andersen: Product Care Information', 'https://www.andersenwindows.com/-/media/Project/AndersenCorporation/AndersenWindows/AndersenWindows/files/technical-docs/care-and-maintenance/9184628.pdf'),
  structure: source('FEMA: Foundation Issues and Pre-Existing Damage', 'https://emilms.fema.gov/IS1104/groups/261.html'),
  gas: source('Piedmont Natural Gas: Identify a Natural Gas Leak', 'https://news.duke-energy.com/releases/piedmont-natural-gas-reminds-customers-how-to-identify-a-natural-gas-leak'),
  mecklenburgPermitting: researchedSource('Mecklenburg County Code Enforcement: Permitting', 'https://code.mecknc.gov/permitting'),
  mecklenburgHomeownerPermitting: researchedSource('Mecklenburg County Code Enforcement: Homeowner Internet Permitting', 'https://code.mecknc.gov/permitting/hip'),
  mecklenburgTradePermitting: researchedSource('Mecklenburg County Code Enforcement: Trade Internet Permitting', 'https://code.mecknc.gov/permitting/tip'),
  mecklenburgCodeSupport: researchedSource('Mecklenburg County Code Enforcement: Support', 'https://code.mecknc.gov/support'),
  epaCarbonMonoxide: researchedSource('U.S. EPA: Carbon Monoxide Poisoning — Protect Your Family and Yourself', 'https://www.epa.gov/indoor-air-quality-iaq/carbon-monoxide-poisoning-protect-your-family-and-yourself-factsheet'),
  cdcCarbonMonoxide: researchedSource('U.S. CDC: Carbon Monoxide Poisoning Basics', 'https://www.cdc.gov/carbon-monoxide/about/index.html'),
  cpscCarbonMonoxide: researchedSource('U.S. CPSC: Carbon Monoxide Information Center', 'https://www.cpsc.gov/Safety-Education/Safety-Education-Centers/Carbon-Monoxide-Information-Center'),
  epaMoldCleanup: researchedSource('U.S. EPA: Mold Cleanup in Your Home', 'https://www.epa.gov/mold/mold-cleanup-your-home'),
  epaFloodCleanup: researchedSource('U.S. EPA: Flood Cleanup to Protect Indoor Air and Your Health', 'https://www.epa.gov/emergencies-iaq/flood-cleanup-protect-indoor-air-and-your-health'),
  cdcMoldCleanup: researchedSource('U.S. CDC: Mold Cleanup in Your Home', 'https://www.cdc.gov/mold-health/about/clean-up.html'),
  energyStarHvacMaintenance: researchedSource('U.S. ENERGY STAR: HVAC Maintenance Checklist', 'https://www.energystar.gov/saveathome/heating-cooling/maintenance-checklist'),
  doeAcMaintenance: researchedSource('U.S. Department of Energy: Maintaining Your Air Conditioner', 'https://www.energy.gov/energysaver/maintaining-your-air-conditioner'),
  epaSection608: researchedSource('U.S. EPA: Section 608 Technician Certification', 'https://www.epa.gov/section608/section-608-technician-certification-0'),
  nfpaElectrical: researchedSource('NFPA: Electrical Safety in the Home', 'https://www.nfpa.org/education-and-research/home-fire-safety/electrical-safety-in-the-home'),
  epaLeadRrp: researchedSource('U.S. EPA: Lead Renovation, Repair and Painting Program', 'https://www.epa.gov/lead/lead-renovation-repair-and-painting-program'),
  epaTermites: researchedSource('U.S. EPA: Termites — How to Identify and Control Them', 'https://www.epa.gov/safepestcontrol/termites-how-identify-and-control-them'),
  npmaPestGuide: researchedSource('NPMA PestWorld: Bug & Insect Identification Guide', 'https://www.pestworld.org/pest-guide/'),
  cdcRodents: researchedSource('U.S. CDC: Controlling Wild Rodent Infestations', 'https://www.cdc.gov/healthy-pets/rodent-control/index.html'),
} as const;
