import { describe, expect, it } from "vitest";
import request from "supertest";
import { createApp, InMemoryRepository, type AuthAdapter, type StripePayments } from "./app.js";
import { reconcilePayments } from "./jobs/reconcilePayments.js";
import { checkedStripeAmount, compositeQuoteScore, SupabaseRepository } from "./repository.js";
import { readFileSync } from "node:fs";

const actors={customer:{id:"customer",role:"customer" as const},provider:{id:"provider",role:"provider" as const},operator:{id:"operator",role:"operator" as const},other:{id:"other",role:"customer" as const}};
const auth:AuthAdapter={async authenticate(token){return actors[token as keyof typeof actors]??null}};
const bearer=(token:string)=>({Authorization:`Bearer ${token}`});
class FakeStripe implements StripePayments {
  calls={payment:0,transfer:0,refund:0,reverse:0}; requestId=""; eventId="evt_1"; objectId="pi_1"; eventType="payment_intent.succeeded"; disputeStatus="needs_response"; amount=0; transfers=new Map<string,string>(); releaseTransfer?:()=>void;
  async createCustomerPayment(){this.calls.payment++;return{id:`pi_${this.calls.payment}`,clientSecret:`pi_${this.calls.payment}_secret_confirm`}}
  async transfer(_amount:number,_destination:string|undefined,key:string){this.calls.transfer++;if(this.releaseTransfer)await new Promise<void>(resolve=>{const prior=this.releaseTransfer!;this.releaseTransfer=()=>{prior();resolve()}});const id=`tr_${this.calls.transfer}`;this.transfers.set(key,id);return id}
  async refund(paymentIntentId:string,amount:number){this.calls.refund++;return `re_${paymentIntentId}_${amount}`}
  async reverse(_transferId:string,amount:number){this.calls.reverse++;return `rv_${amount}_${this.calls.reverse}`}
  async findTransfer(key:string){return this.transfers.get(key)}
  async findReversal(){return undefined}
  constructWebhook(){return{id:this.eventId,type:this.eventType,data:{object:{id:this.objectId,metadata:{requestId:this.requestId},reason:"fraudulent",status:this.disputeStatus,amount:this.amount}}}}
}
const testPaymentApproval=(at:Date)=>({receipt:{mode:"enabled" as const,environmentHash:"1".repeat(64),projectHash:"2".repeat(64),gitSha:"3".repeat(40),migrationHead:"test-migration",capabilityHashes:{payments:"4".repeat(64)},issuedAt:"2026-08-31T00:00:00.000Z",expiresAt:"2026-09-10T00:00:00.000Z",keyId:"test-key",signature:"synthetic"},expectedBinding:{environmentHash:"1".repeat(64),projectHash:"2".repeat(64),gitSha:"3".repeat(40),migrationHead:"test-migration",capabilityHashes:{payments:"4".repeat(64)}},verifySignature:()=>true,now:at});
const setup=(now=()=>new Date("2026-09-01T00:00:00Z"))=>{const repository=new InMemoryRepository(),stripe=new FakeStripe();repository.inspect(s=>{s.providerEligibility.provider={status:"approved",organizationName:"Mint",licenseVerified:true,licenseExpiresAt:"2027-01-01T00:00:00Z",insuranceVerified:true,insuranceExpiresAt:"2027-01-01T00:00:00Z",serviceCategories:["general"],serviceAreas:["Charlotte"]}});return{app:createApp({repository,stripe,auth,paymentsMode:"enabled",paymentApproval:testPaymentApproval(now()),now}),repository,stripe}};
async function quoted(app:ReturnType<typeof createApp>,amountCents=10_003){const r=await request(app).post("/api/requests").set(bearer("customer")).send({customerName:"고객",description:"싱크대 누수 수리가 필요합니다",address:"Charlotte",hazards:["none"]}).expect(201);const requestId=r.body.id as string;await request(app).post(`/api/requests/${requestId}/match`).set(bearer("operator")).send({providerIds:[actors.provider.id]}).expect(200);const q=await request(app).post(`/api/requests/${requestId}/quotes`).set(bearer("provider")).send({providerName:"민트",scope:"진단 및 배관 교체",amountCents,ranking:{totalCents:amountCents,earliestStartAt:"2026-09-02T00:00:00.000Z",warrantyDays:90}}).expect(201);return{requestId,quoteId:q.body.id as string}}
async function confirm(app:ReturnType<typeof createApp>,stripe:FakeStripe,requestId:string,objectId:string,eventId:string){stripe.requestId=requestId;stripe.objectId=objectId;stripe.eventId=eventId;stripe.eventType="payment_intent.succeeded";await request(app).post("/api/webhooks/stripe").set("stripe-signature","valid").set("Content-Type","application/json").send(Buffer.from(`{"id":"${eventId}"}`)).expect(201)}
async function completedAndCaptured(app:ReturnType<typeof createApp>,stripe:FakeStripe,amount=10_003){const q=await quoted(app,amount);const dep=await request(app).post(`/api/requests/${q.requestId}/deposit`).set(bearer("customer")).set("Idempotency-Key","dep-1").send({quoteId:q.quoteId}).expect(202);expect(dep.body.clientSecret).toContain("_secret_");await confirm(app,stripe,q.requestId,dep.body.providerReference,"evt_dep");await request(app).post(`/api/requests/${q.requestId}/start`).set(bearer("provider")).send({}).expect(200);for(const kind of["before","after"])await request(app).post(`/api/requests/${q.requestId}/evidence`).set(bearer("provider")).send({kind,note:`${kind} evidence`}).expect(201);await request(app).post(`/api/requests/${q.requestId}/complete`).set(bearer("provider")).send({}).expect(200);const bal=await request(app).post(`/api/requests/${q.requestId}/balance`).set(bearer("customer")).set("Idempotency-Key","bal-1").send({}).expect(202);expect(bal.body.providerReference).not.toBe(dep.body.providerReference);await confirm(app,stripe,q.requestId,bal.body.providerReference,"evt_bal");return q}

const settle=async(app:ReturnType<typeof createApp>,requestId:string,key="transfer")=>{const pre=await request(app).post(`/api/requests/${requestId}/settlement-preflight`).set(bearer("operator")).send({}).expect(200);return request(app).post(`/api/requests/${requestId}/settle`).set(bearer("operator")).set("Idempotency-Key",key).send(pre.body).expect(201)};

describe("protected deployment readiness",()=>{
  const hash=(digit:string)=>digit.repeat(64);
  const manifest={schemaVersion:1 as const,environmentHash:hash("1"),projectHash:hash("2"),apiOriginHash:hash("3"),gitSha:"4".repeat(40),migrationHead:"202609060001_release",capabilityResultHashes:{payments:hash("5"),database:hash("6")},evidenceHashes:{tests:hash("7")},approvalReceiptId:"approval-key-1",rotationOwner:"platform-operations",revocationOwner:"security-operations",paymentsMode:"enabled" as const};
  const paymentApproval={receipt:{mode:"enabled",environmentHash:manifest.environmentHash,projectHash:manifest.projectHash,gitSha:manifest.gitSha,migrationHead:manifest.migrationHead,capabilityHashes:manifest.capabilityResultHashes,issuedAt:"2026-08-31T00:00:00.000Z",expiresAt:"2026-09-02T00:00:00.000Z",keyId:manifest.approvalReceiptId,signature:"synthetic"},expectedBinding:{environmentHash:manifest.environmentHash,projectHash:manifest.projectHash,gitSha:manifest.gitSha,migrationHead:manifest.migrationHead,capabilityHashes:manifest.capabilityResultHashes},verifySignature:()=>true,now:new Date("2026-09-01T00:00:00.000Z")};
  it("requires an allowlisted operator and exposes only states and hashes",async()=>{const app=createApp({repository:new InMemoryRepository(),stripe:new FakeStripe(),auth,operatorAllowlist:["operator"],paymentsMode:"enabled",paymentApproval,deploymentManifest:manifest});await request(app).get("/api/ops/readiness").expect(401);await request(app).get("/api/ops/readiness").set(bearer("customer")).expect(403);const response=await request(app).get("/api/ops/readiness").set(bearer("operator")).expect(200);expect(response.body).toMatchObject({ready:true,payments:{mode:"enabled",state:"ready"},capabilities:{database:{state:"bound",resultHash:hash("6")},payments:{state:"bound",resultHash:hash("5")}}});const serialized=JSON.stringify(response.body);expect(serialized).not.toContain(manifest.approvalReceiptId);expect(serialized).not.toContain(manifest.rotationOwner);expect(serialized).not.toContain(manifest.revocationOwner);expect(serialized).not.toContain(manifest.migrationHead);});
  it("fails closed when payment mode or receipt identity does not match",async()=>{const identityMismatch=createApp({repository:new InMemoryRepository(),stripe:new FakeStripe(),auth,operatorAllowlist:["operator"],paymentsMode:"enabled",paymentApproval,deploymentManifest:{...manifest,approvalReceiptId:"different-approval"}});const identityResponse=await request(identityMismatch).get("/api/ops/readiness").set(bearer("operator")).expect(503);expect(identityResponse.body).toMatchObject({ready:false,payments:{mode:"enabled",state:"blocked"}});const modeMismatch=createApp({repository:new InMemoryRepository(),auth,operatorAllowlist:["operator"],paymentsMode:"disabled",paymentApproval,deploymentManifest:{...manifest,paymentsMode:"disabled"}});const modeResponse=await request(modeMismatch).get("/api/ops/readiness").set(bearer("operator")).expect(503);expect(modeResponse.body).toMatchObject({ready:false,payments:{mode:"disabled",state:"blocked"}});});
});

describe("money lifecycle",()=>{
  it("denies assigned providers immediately when suspended or credentials expire",async()=>{const{app,repository}=setup();const q=await quoted(app);repository.inspect(s=>{s.providerEligibility.provider.status="suspended"});expect(((await repository.dashboard(actors.provider,"")) as {requests:unknown[]}).requests).toHaveLength(0);await request(app).post(`/api/requests/${q.requestId}/quotes`).set(bearer("provider")).send({providerName:"blocked",scope:"blocked scope",amountCents:1000,ranking:{totalCents:1000,earliestStartAt:"2026-09-02T00:00:00.000Z",warrantyDays:0}}).expect(403);repository.inspect(s=>{s.providerEligibility.provider.status="approved";s.providerEligibility.provider.licenseExpiresAt="2026-01-01T00:00:00Z"});await request(app).post(`/api/requests/${q.requestId}/evidence`).set(bearer("provider")).send({kind:"before",note:"expired credential"}).expect(403);expect(((await repository.dashboard(actors.provider,"")) as {requests:unknown[]}).requests).toHaveLength(0)});
  it("rejects Stripe operation overflow before provider side effects",async()=>{expect(()=>checkedStripeAmount("100000000")).toThrow("stripe_amount_out_of_range");expect(()=>checkedStripeAmount("9007199254740992")).toThrow("stripe_amount_out_of_range");expect(checkedStripeAmount("99999999")).toBe(99_999_999);const{app,stripe}=setup();const q=await quoted(app,99_999_999);await request(app).post(`/api/requests/${q.requestId}/quotes`).set(bearer("provider")).send({providerName:"duplicate",scope:"duplicate scope",amountCents:99_999_999,ranking:{totalCents:99_999_999,earliestStartAt:"2026-09-03T00:00:00.000Z",warrantyDays:0}}).expect(409);expect(stripe.calls.payment).toBe(0)});
  it("returns separate confirmable deposit and balance PaymentIntents",async()=>{const{app,stripe,repository}=setup();const q=await completedAndCaptured(app,stripe,10_003);expect(stripe.calls.payment).toBe(2);expect(repository.inspect(s=>s.payments.filter(p=>p.requestId===q.requestId&&p.status==="succeeded").map(p=>[p.kind,p.amountCents]))).toEqual([["deposit",2001],["balance",8002]])});
  it("selects one effective versioned fee policy and binds its immutable snapshot",async()=>{let clock=new Date("2026-09-01T00:00:00Z");const{app,stripe,repository}=setup(()=>clock);const q=await completedAndCaptured(app,stripe,10_000);clock=new Date("2026-09-04T00:00:00Z");const pre=await request(app).post(`/api/requests/${q.requestId}/settlement-preflight`).set(bearer("operator")).send({}).expect(200);expect(pre.body).toMatchObject({feeVersion:1,feeRateBps:1000,feeAmountCents:1000,capturedAmountCents:10000,transferAmountCents:9000});expect(repository.inspect(s=>s.jobs[q.requestId].feeSnapshot)).toMatchObject({policyId:"standard-v1",taxRateBps:0,stripeFeeTreatment:"included",refundTreatment:"fee_retained",rounding:"half_up"});await request(app).post(`/api/requests/${q.requestId}/settle`).set(bearer("operator")).set("Idempotency-Key","tampered").send({...pre.body,feeAmountCents:999}).expect(409);expect(stripe.calls.transfer).toBe(0)});
  it("replays a completed settlement only for the original key and blocks terminal reauthorization",async()=>{let clock=new Date("2026-09-01T00:00:00Z");const{app,stripe}=setup(()=>clock);const q=await completedAndCaptured(app,stripe,10_000);clock=new Date("2026-09-04T00:00:00Z");const pre=await request(app).post(`/api/requests/${q.requestId}/settlement-preflight`).set(bearer("operator")).send({}).expect(200);await request(app).post(`/api/requests/${q.requestId}/settle`).set(bearer("operator")).set("Idempotency-Key","terminal").send(pre.body).expect(201);await request(app).post(`/api/requests/${q.requestId}/settle`).set(bearer("operator")).set("Idempotency-Key","terminal").send(pre.body).expect(200);await request(app).post(`/api/requests/${q.requestId}/settlement-preflight`).set(bearer("operator")).send({}).expect(409);expect(stripe.calls.transfer).toBe(1)});
  it("fails closed at deposit finalization when fee policy selection is empty",async()=>{const{app,stripe,repository}=setup();const q=await quoted(app,10_000);repository.inspect(s=>s.feePolicies).splice(0);const dep=await request(app).post(`/api/requests/${q.requestId}/deposit`).set(bearer("customer")).set("Idempotency-Key","dep-policy").send({quoteId:q.quoteId}).expect(202);stripe.requestId=q.requestId;stripe.objectId=dep.body.providerReference;await request(app).post("/api/webhooks/stripe").set("stripe-signature","valid").set("Content-Type","application/json").send(Buffer.from("{}")).expect(500)});
  it("allocates refunds across customer charges and never refunds a provider transfer",async()=>{let clock=new Date("2026-09-01T00:00:00Z");const{app,stripe,repository}=setup(()=>clock);const q=await completedAndCaptured(app,stripe,10_000);clock=new Date("2026-09-04T00:00:00Z");await settle(app,q.requestId);await request(app).post(`/api/requests/${q.requestId}/reviews`).set(bearer("customer")).send({rating:5,text:"Excellent completed repair"}).expect(201);await request(app).post(`/api/requests/${q.requestId}/refunds`).set(bearer("operator")).set("Idempotency-Key","refund").send({amountCents:2500,reason:"합의 환불"}).expect(201);expect(stripe.calls.refund).toBe(2);expect(repository.inspect(s=>s.payments.filter(p=>p.kind==="refund").map(p=>p.amountCents))).toEqual([2000,500]);expect(repository.inspect(s=>s.payments.find(p=>p.kind==="transfer")?.amountCents)).toBe(9000)});
  it("ingests every dispute event and recovers a won reversal with a new-version transfer",async()=>{let clock=new Date("2026-09-01T00:00:00Z");const{app,stripe,repository}=setup(()=>clock);const q=await completedAndCaptured(app,stripe,10_000);clock=new Date("2026-09-04T00:00:00Z");await settle(app,q.requestId);stripe.requestId=q.requestId;stripe.objectId="dp_1";stripe.amount=3000;for(const [eventId,eventType,status] of [["evt_a","charge.dispute.created","needs_response"],["evt_b","charge.dispute.updated","under_review"],["evt_c","charge.dispute.closed","won"]]){stripe.eventId=eventId;stripe.eventType=eventType;stripe.disputeStatus=status;await request(app).post("/api/webhooks/stripe").set("stripe-signature","valid").set("Content-Type","application/json").send(Buffer.from(`{"id":"${eventId}"}`)).expect(201)}expect(Object.keys(repository.inspect(s=>s.webhookEvents))).toHaveLength(3);expect(stripe.calls.reverse).toBe(1);expect(repository.inspect(s=>Object.values(s.disputes)[0].status)).toBe("won");expect(repository.inspect(s=>s.jobs[q.requestId].settlementState)).toBe("reconciliation_required");clock=new Date("2026-09-04T00:10:00Z");const result=await reconcilePayments(repository,stripe,clock);expect(result.completed).toBe(1);expect(repository.inspect(s=>s.jobs[q.requestId].settlementState)).toBe("settled")});
  it("marks transferring disputes for reconciliation and recovers them after the transfer barrier",async()=>{let clock=new Date("2026-09-01T00:00:00Z");const{app,stripe,repository}=setup(()=>clock);const q=await completedAndCaptured(app,stripe,10_000);clock=new Date("2026-09-04T00:00:00Z");const pre=await request(app).post(`/api/requests/${q.requestId}/settlement-preflight`).set(bearer("operator")).send({}).expect(200);stripe.releaseTransfer=()=>{};const pending=request(app).post(`/api/requests/${q.requestId}/settle`).set(bearer("operator")).set("Idempotency-Key","race").send(pre.body).then(v=>v);await new Promise(resolve=>setTimeout(resolve,10));stripe.requestId=q.requestId;stripe.objectId="dp_race";stripe.eventId="evt_race";stripe.eventType="charge.dispute.created";stripe.amount=3000;await request(app).post("/api/webhooks/stripe").set("stripe-signature","valid").set("Content-Type","application/json").send(Buffer.from("{}"));expect(repository.inspect(s=>s.jobs[q.requestId].settlementState)).toBe("reconciliation_required");stripe.releaseTransfer!();await pending;expect(repository.inspect(s=>s.jobs[q.requestId].settlementState)).toBe("reconciliation_required");clock=new Date("2026-09-04T00:10:00Z");const summary=await reconcilePayments(repository,stripe,clock);expect(summary.inspected).toBeGreaterThanOrEqual(1);expect(summary).toMatchObject({completed:1,failed:0});expect(stripe.calls.reverse).toBe(1);expect(repository.inspect(s=>s.jobs[q.requestId].settlementState)).toBe("manual_action")});
});


describe("Supabase repository money contract",()=>{
  it("uses real RPCs when configured and otherwise emits an explicit integration diagnostic",async()=>{
    const url=process.env.SUPABASE_TEST_URL,anon=process.env.SUPABASE_TEST_ANON_KEY,service=process.env.SUPABASE_TEST_SERVICE_ROLE_KEY;
    if(!url||!anon||!service){if(process.env.REQUIRE_SUPABASE_INTEGRATION==="1")throw new Error("required Supabase integration environment is absent");expect(process.env.REQUIRE_SUPABASE_INTEGRATION).not.toBe("1");return;}
    const repository=new SupabaseRepository(url,anon,service);
    const claims=await repository.stuckMoneyClaims(new Date(0).toISOString());
    expect(Array.isArray(claims)).toBe(true);
    const recovery=await repository.completeMoney("recovery","00000000-0000-0000-0000-000000000000",undefined,{actor:actors.operator,accessToken:"",now:new Date().toISOString()});
    expect(recovery.status).toBe(409);
    expect(JSON.stringify(recovery.data)).not.toMatch(/function .* does not exist|schema cache/i);
    await expect(repository.dashboard(actors.customer,"invalid-integration-token")).rejects.toBeTruthy();
  });
});

describe("P0 backend contracts",()=>{
  it("persists structured surfaces, hides low-sample price, and blocks hazards",async()=>{const{app}=setup();const q=await quoted(app);const payload={workScope:{symptom:"Leaking trap",location:"Kitchen sink",dimensions:"1.5 inch",access:"open",desiredTime:"2026-09-08T00:00:00.000Z",photos:[],exclusions:["cabinet"]},triage:{category:"plumbing",urgency:"routine",possibleCauses:["loose trap"],confidence:.8,questions:["When?"],hazards:[]},priceDisclosure:{source:"regional",sampleCount:12,updatedAt:"2026-09-05T00:00:00.000Z",confidence:.5,priceCents:10000}};const saved=await request(app).post(`/api/requests/${q.requestId}/details`).set(bearer("customer")).send(payload).expect(200);expect(saved.body.priceDisclosure.priceCents).toBeUndefined();await request(app).post(`/api/requests/${q.requestId}/details`).set(bearer("customer")).send(payload).expect(409);const q2=await quoted(app);await request(app).post(`/api/requests/${q2.requestId}/details`).set(bearer("customer")).send({...payload,triage:{...payload.triage,hazards:["gas"]}}).expect(400)});
  it("validates privacy, scope disclosure, provider slots, evidence, messaging, and scheduling",async()=>{const{app,stripe}=setup();await request(app).post("/api/privacy/deletion").set(bearer("customer")).send({}).expect(409);await request(app).post("/api/privacy/consent").set(bearer("customer")).send({version:"2026-09",accepted:true}).expect(201);const q=await quoted(app);await request(app).post(`/api/requests/${q.requestId}/provider-slot`).set(bearer("operator")).send({providerId:"provider-new"}).expect(201);await request(app).post(`/api/requests/${q.requestId}/details`).set(bearer("customer")).send({workScope:"Replace leaking kitchen drain",triage:{urgency:"routine",occupied:true,utilitiesShutoffKnown:true},priceDisclosureAccepted:true}).expect(200);const dep=await request(app).post(`/api/requests/${q.requestId}/deposit`).set(bearer("customer")).set("Idempotency-Key","p0-dep").send({quoteId:q.quoteId}).expect(202);await confirm(app,stripe,q.requestId,dep.body.providerReference,"evt-p0-dep");await request(app).post(`/api/requests/${q.requestId}/start`).set(bearer("provider")).send({}).expect(200);for(const kind of["receipt","warranty"])await request(app).post(`/api/requests/${q.requestId}/evidence`).set(bearer("provider")).send({kind,note:`${kind} evidence`}).expect(201);await request(app).post(`/api/requests/${q.requestId}/messages`).set(bearer("provider")).send({text:"Arrival window confirmed"}).expect(201);await request(app).put(`/api/requests/${q.requestId}/schedule`).set(bearer("customer")).send({startsAt:"2026-09-05T14:00:00.000Z",timeZone:"America/New_York",status:"confirmed"}).expect(200);await request(app).post("/api/privacy/deletion").set(bearer("customer")).send({}).expect(202)});
  it("rejects incomplete P0 payloads and retired media routes",async()=>{const{app}=setup();const q=await quoted(app);await request(app).post(`/api/requests/${q.requestId}/details`).set(bearer("customer")).send({workScope:"short",priceDisclosureAccepted:false}).expect(400);await request(app).post(`/api/requests/${q.requestId}/media`).set(bearer("customer")).send({}).expect(404);await request(app).post("/api/media/retired/upload-url").set(bearer("customer")).send({}).expect(404);await request(app).post("/api/media/retired/complete").set(bearer("customer")).send({}).expect(404);await request(app).patch("/api/media/retired/sanitization").set(bearer("operator")).send({}).expect(404);await request(app).post(`/api/requests/${q.requestId}/changes`).set(bearer("provider")).send({description:"extra",amountCents:100}).expect(400)});
  it("has one prefixed production money RPC surface with RLS, limits, webhook and recovery grants",()=>{const sql=readFileSync("supabase/migrations/0001_mvp.sql","utf8");expect(sql).not.toContain("113608");for(const tag of["$$","$won_recovery$","$provider_key$","$booking_fee$","$settlement_preflight$","$recovery_complete$","$recovery_fail$"])expect(sql.split(tag).length%2).toBe(1);expect(sql.match(/create function settlement_claim\(/g)).toHaveLength(1);expect(sql).not.toContain("deposit_succeeded_claim");expect(sql).toMatch(/create function recovery_complete\(p_claim_id uuid,p_provider_reference text,p_detail jsonb\)/);expect(sql).toMatch(/grant execute on function [^;]*recovery_complete\(uuid,text,jsonb\),recovery_fail\(uuid,text\) to service_role/);expect(sql).toMatch(/provider_idempotency_key text unique/);expect(sql).toMatch(/amount_cents between 0 and 99999999/);expect(sql).toMatch(/quotes_one_per_provider_request/);expect(sql).toMatch(/force row level security/);expect(sql).toMatch(/stripe_webhook_events/);expect(sql).toMatch(/jobs_snapshot_booking_fee/)});
  it("uses p-prefixed parameters and v-prefixed non-column locals in every reachable money RPC",()=>{const sql=readFileSync("supabase/migrations/0001_mvp.sql","utf8");const names=["customer_payment_complete","payment_succeeded_claim","payment_succeeded_complete","settlement_complete","refund_claim","refund_complete","external_dispute_claim","external_dispute_complete","recovery_complete"];for(const name of names){const start=sql.indexOf(`function ${name}(`),end=sql.indexOf("end;",start),definition=sql.slice(start,end),parameters=definition.slice(definition.indexOf("(")+1,definition.indexOf(")")).split(","),declarations=definition.match(/\bdeclare\s+([\s\S]*?)\bbegin\b/)?.[1]??"";expect(start,`${name} exists`).toBeGreaterThanOrEqual(0);expect(parameters.every(parameter=>parameter.trim().startsWith("p_")),`${name} parameters`).toBe(true);expect(declarations,`${name} locals`).not.toMatch(/(?:^|;)\s*(?!v_)[a-z][a-z0-9_]*\s+/i);expect(declarations,`${name} column-named locals`).not.toMatch(/(?:^|;)\s*(id|request_id|provider_reference|event_id|state|kind|amount_cents)\s+/i)}});
  it("opens internal disputes through a definer RPC with qualified atomic hold invalidation",()=>{const sql=readFileSync("supabase/migrations/0001_mvp.sql","utf8");const start=sql.indexOf("function open_internal_dispute("),end=sql.indexOf("end; $$;",start),definition=sql.slice(start,end);expect(definition).toMatch(/security definer/);expect(definition).toMatch(/declare v_result disputes; v_completed_at timestamptz; v_now timestamptz/);expect(definition).not.toMatch(/declare[^;]*\b(result|request_id|source|reason|completed)\b/);expect(definition).toMatch(/r\.customer_id=auth\.uid\(\)/);expect(definition).toMatch(/v_now<v_completed_at or v_now>=v_completed_at\+interval '72 hours'/);expect(definition).toMatch(/set dispute_status='open',authorization_version=j\.authorization_version\+1,authorization_token=null/);expect(definition).toMatch(/delete from settlement_authorizations sa where sa\.request_id=p_request_id/);});
});


describe("P0 persisted ranking, read model, and audit",()=>{
  it("persists a versioned multi-factor score instead of ordering by lowest price",async()=>{const{app}=setup();const q=await quoted(app,25_000);const dashboard=await request(app).get("/api/dashboard").set(bearer("customer")).expect(200);expect(dashboard.body.quotes[0]).toMatchObject({id:q.quoteId,rankingPolicyVersion:1});expect(dashboard.body.quotes[0].rankingScore).toBeGreaterThan(0);const created=dashboard.body.quotes[0];expect(compositeQuoteScore(created)).toBe(created.rankingScore);const expensive={...created,id:"better",amountCents:30_000,rankingScore:created.rankingScore+1};expect([created,expensive].sort((a,b)=>compositeQuoteScore(b)-compositeQuoteScore(a))[0].id).toBe("better")});
  it("returns persisted P0 request surfaces after dashboard refresh with tenant scope",async()=>{const{app}=setup();await request(app).post("/api/privacy/consent").set(bearer("customer")).send({version:"2026-09",accepted:true}).expect(201);const q=await quoted(app);await request(app).post(`/api/requests/${q.requestId}/messages`).set(bearer("customer")).send({text:"Persist this message"}).expect(201);await request(app).put(`/api/requests/${q.requestId}/schedule`).set(bearer("customer")).send({startsAt:"2026-09-10T10:00:00.000Z",timeZone:"America/New_York",status:"confirmed"}).expect(200);const dashboard=await request(app).get("/api/dashboard").set(bearer("customer")).expect(200);expect(dashboard.body.media).toHaveLength(0);expect(dashboard.body.messages[0].text).toBe("Persist this message");expect(dashboard.body.schedules[0].status).toBe("confirmed");expect(dashboard.body.privacy.consents[0].consentVersion).toBe("2026-09");const other=await request(app).get("/api/dashboard").set(bearer("other")).expect(200);expect(other.body.media).toHaveLength(0);expect(other.body.messages).toHaveLength(0)});
  it("records correlated rationale-bearing audits and defines atomic production audit triggers",async()=>{const{app,repository}=setup();const q=await quoted(app);const audits=repository.inspect(state=>state.audit.filter(event=>event.requestId===q.requestId));expect(audits.length).toBeGreaterThan(0);expect(audits.every(event=>event.actorId&&event.action&&event.resourceType&&event.resourceId&&event.rationale&&event.correlationId)).toBe(true);const sql=readFileSync("supabase/migrations/0001_mvp.sql","utf8");expect(sql).toMatch(/create table ranking_policies/);expect(sql).toMatch(/policy_version bigint not null references ranking_policies\(version\),score numeric not null/);for(const field of["resource_type text not null","resource_id text not null","rationale text not null","correlation_id text not null"])expect(sql).toContain(field);expect(sql).toMatch(/create function audit_domain_mutation\(\)/);expect(sql).toMatch(/create trigger audit_money_operations_mutation/);expect(sql).toMatch(/create trigger audit_request_media_mutation/)});
});
