/**
 * B2B 관리 화면: 조직/지점/멤버 관리, 견적 승인, 연간 리포트.
 */
import { dollars, useRemote, useTask, words } from './state';
import { useState } from 'react';
import { Text, View } from 'react-native';
import { z } from 'zod';
import { post } from '../platform/api';
import { Action, styles } from '../chat/ui';
import { Field, Screen, Section, type ManagementProps } from './shared';
const organization = z.object({ id: z.string(), owner_id: z.string(), name: z.string() });
const listSchema = z.object({ organizations: z.array(organization) });
const detailSchema = z.object({ organization, members: z.array(z.object({ profile_id: z.string(), role: z.string() })), locations: z.array(z.object({ id: z.string(), name: z.string(), address: z.string() })), requests: z.array(z.object({ request_id: z.string(), location_id: z.string(), business_interruption: z.boolean(), impact_note: z.string() })), approvals: z.array(z.object({ id: z.string(), request_id: z.string(), quote_id: z.string(), amount_cents: z.number(), status: z.string(), requested_by: z.string() })) });
const reportSchema = z.object({ report: z.object({ year: z.number(), request_count: z.number(), completed_count: z.number(), interruption_count: z.number(), paid_cents: z.number(), refunded_cents: z.number(), net_paid_cents: z.number(), locations: z.array(z.object({ location_id: z.string(), name: z.string(), request_count: z.number(), paid_cents: z.number(), refunded_cents: z.number() })) }) });
const saved = z.object({}).passthrough();
export function BusinessScreen(props: ManagementProps) {
  const { locale, accessToken } = props; const t = (en: string, es: string) => words(locale, en, es); const remote = useRemote('/api/business/organizations', accessToken, listSchema, locale); const task = useTask(locale);
  const [name, setName] = useState(''); const [selected, setSelected] = useState('');
  if (selected) return <OrganizationScreen {...props} organizationId={selected} onBack={() => { setSelected(''); void remote.reload(); }} />;
  return <Screen {...props} title={t('Business locations', 'Locales del negocio')}>{remote.feedback}{remote.data?.organizations.map(org => <Action key={org.id} label={org.name} onPress={() => setSelected(org.id)} />)}{remote.data?.organizations.length === 0 && <Text style={styles.body}>{t('Create an organization to track repairs across locations and request expense approval.', 'Crea una organización para gestionar reparaciones en varios locales y solicitar autorización de gastos.')}</Text>}<Section title={t('Create organization', 'Crear organización')}><Field label={t('Organization name', 'Nombre de la organización')} value={name} onChange={setName} />{task.feedback}<Action primary disabled={task.busy || !name.trim()} label={t('Create organization', 'Crear organización')} onPress={() => void task.run(async () => { const result = await post('/api/business/organizations', accessToken, z.object({ organization }), { name }); setSelected(result.organization.id); }, '')} /></Section></Screen>;
}
function OrganizationScreen(props: ManagementProps & { readonly organizationId: string }) {
  const { locale, accessToken: token, organizationId: id } = props; const t = (en: string, es: string) => words(locale, en, es); const base = `/api/business/organizations/${id}`;
  const remote = useRemote(base, token, detailSchema, locale); const task = useTask(locale);
  const [locationName, setLocationName] = useState(''); const [address, setAddress] = useState(''); const [member, setMember] = useState(''); const [approver, setApprover] = useState(false); const [note, setNote] = useState(''); const [year, setYear] = useState(String(new Date().getFullYear())); const [showReport, setShowReport] = useState(false); const [linking, setLinking] = useState(false);
  const save = (path: string, body: unknown) => void task.run(async () => { await post(path, token, saved, body); await remote.reload(); }, t('Saved.', 'Guardado.'));
  if (showReport) return <AnnualReport {...props} year={year} onBack={() => setShowReport(false)} />;
  if (linking) return <LinkRequest {...props} detail={remote.data} onBack={() => { setLinking(false); void remote.reload(); }} />;
  return <Screen {...props} title={remote.data?.organization.name ?? t('Organization', 'Organización')}>{remote.feedback}{task.feedback}
    <Section title={t('Locations', 'Locales')}>{remote.data?.locations.map(item => <View key={item.id}><Text style={styles.heading}>{item.name}</Text><Text style={styles.body}>{item.address}</Text></View>)}<Field label={t('Location name', 'Nombre del local')} value={locationName} onChange={setLocationName} /><Field label={t('Full address', 'Dirección completa')} value={address} onChange={setAddress} /><Text style={styles.muted}>{t('The owner or an approver can add locations.', 'El propietario o un aprobador puede añadir locales.')}</Text><Action disabled={task.busy || !locationName.trim() || !address.trim()} label={t('Add location', 'Añadir local')} onPress={() => save(`${base}/locations`, { name: locationName, address })} /></Section>
    <Section title={t('Location repairs', 'Reparaciones por local')}><Action label={t('Link one of my requests', 'Vincular una solicitud mía')} onPress={() => setLinking(true)} />{remote.data?.requests.map(item => <View key={item.request_id}><Text selectable style={styles.body}>{item.request_id}</Text><Text style={styles.muted}>{item.business_interruption ? t('Business interrupted', 'Actividad interrumpida') : t('Normal priority', 'Prioridad normal')} {item.impact_note}</Text></View>)}</Section>
    <Section title={t('Expense approvals', 'Autorizaciones de gastos')}><Text style={styles.muted}>{t('Approval authorizes an internal expense only. It does not book a job or charge a card. You cannot approve your own request.', 'La aprobación solo autoriza un gasto interno. No reserva un trabajo ni cobra a una tarjeta. No puedes aprobar tu propia solicitud.')}</Text><Field multiline label={t('Decision note', 'Motivo de la decisión')} value={note} onChange={setNote} />{remote.data?.approvals.map(item => <View key={item.id} style={styles.separator}><Text style={styles.heading}>{dollars(item.amount_cents, locale)}</Text><Text style={styles.body}>{item.status === 'approved' ? t('Approved', 'Aprobado') : item.status === 'rejected' ? t('Rejected', 'Rechazado') : t('Awaiting decision', 'Pendiente de decisión')}</Text><Text selectable style={styles.muted}>{item.request_id}</Text>{item.status === 'pending' && <><Action label={t('Approve expense', 'Aprobar gasto')} disabled={task.busy || !note.trim()} onPress={() => save(`/api/business/approvals/${item.id}/decision`, { decision: 'approved', note })} /><Action label={t('Reject expense', 'Rechazar gasto')} disabled={task.busy || !note.trim()} onPress={() => save(`/api/business/approvals/${item.id}/decision`, { decision: 'rejected', note })} /></>}</View>)}</Section>
    <Section title={t('Team access', 'Acceso del equipo')}><Text style={styles.muted}>{t('Only the organization owner can add an existing customer account. No invitation is sent. Members can see business repair references and spending, but not private repair media.', 'Solo el propietario puede añadir una cuenta de cliente existente. No se envía invitación. Los miembros pueden ver referencias de reparaciones y gastos, pero no fotos privadas.')}</Text>{remote.data?.members.map(item => <Text key={item.profile_id} selectable style={styles.muted}>{item.profile_id} · {item.role === 'approver' ? t('Approver', 'Aprobador') : t('Member', 'Miembro')}</Text>)}<Field label={t('Existing customer account ID', 'ID de cuenta de cliente existente')} value={member} onChange={setMember} /><Action label={approver ? t('Role: approver (tap to change)', 'Rol: aprobador (toca para cambiar)') : t('Role: member (tap to change)', 'Rol: miembro (toca para cambiar)')} onPress={() => setApprover(value => !value)} /><Action disabled={task.busy || !member.trim()} label={t('Save team member', 'Guardar miembro')} onPress={() => save(`${base}/members`, { profileId: member, role: approver ? 'approver' : 'member' })} /></Section>
    <Section title={t('Annual spending', 'Gastos anuales')}><Field numeric label={t('Year', 'Año')} value={year} onChange={setYear} /><Action disabled={!/^\d{4}$/.test(year)} label={t('View annual report', 'Ver informe anual')} onPress={() => setShowReport(true)} /></Section>
  </Screen>;
}
function AnnualReport(props: ManagementProps & { readonly organizationId: string; readonly year: string }) {
  const { locale, accessToken, organizationId, year } = props; const t = (en: string, es: string) => words(locale, en, es); const remote = useRemote(`/api/business/organizations/${organizationId}/report?year=${year}`, accessToken, reportSchema, locale); const value = remote.data?.report;
  return <Screen {...props} title={`${t('Annual report', 'Informe anual')} ${year}`}>{remote.feedback}<Text style={styles.muted}>{t('Recorded payments and refunds for the UTC calendar year. No projected savings.', 'Pagos y reembolsos registrados en el año calendario UTC. No incluye ahorros estimados.')}</Text>{value && <><Text style={styles.heading}>{t('Net paid', 'Pago neto')}: {dollars(value.net_paid_cents, locale)}</Text><Text style={styles.body}>{t('Payments', 'Pagos')}: {dollars(value.paid_cents, locale)}</Text><Text style={styles.body}>{t('Refunds', 'Reembolsos')}: {dollars(value.refunded_cents, locale)}</Text><Text style={styles.body}>{value.request_count} {t('requests', 'solicitudes')} · {value.completed_count} {t('completed', 'terminadas')} · {value.interruption_count} {t('interruptions', 'interrupciones')}</Text>{value.locations.map(item => <Section key={item.location_id} title={item.name}><Text style={styles.body}>{item.request_count} {t('requests', 'solicitudes')}</Text><Text style={styles.body}>{t('Paid', 'Pagado')}: {dollars(item.paid_cents, locale)} · {t('Refunded', 'Reembolsado')}: {dollars(item.refunded_cents, locale)}</Text></Section>)}</>}</Screen>;
}
const mineSchema = z.object({ requests: z.array(z.object({ id: z.string(), description: z.string(), address: z.string() })), quotes: z.array(z.object({ id: z.string(), requestId: z.string(), providerName: z.string(), amountCents: z.number() })) });
function LinkRequest(props: ManagementProps & { readonly organizationId: string; readonly detail: z.infer<typeof detailSchema> | null }) {
  const { locale, accessToken: token, organizationId: id, detail } = props; const t = (en: string, es: string) => words(locale, en, es); const remote = useRemote('/api/dashboard', token, mineSchema, locale); const task = useTask(locale); const [requestId, setRequestId] = useState(''); const [locationId, setLocationId] = useState(''); const [impact, setImpact] = useState(''); const [interrupted, setInterrupted] = useState(false);
  return <Screen {...props} title={t('Link repair and approval', 'Vincular reparación y autorización')}>{remote.feedback}{task.feedback}<Section title={t('Choose request', 'Elegir solicitud')}>{remote.data?.requests.map(item => <Action key={item.id} primary={item.id === requestId} label={`${item.description} · ${item.address}`} onPress={() => setRequestId(item.id)} />)}</Section><Section title={t('Choose location', 'Elegir local')}>{detail?.locations.map(item => <Action key={item.id} primary={item.id === locationId} label={`${item.name} · ${item.address}`} onPress={() => setLocationId(item.id)} />)}</Section><Action label={interrupted ? t('Business interrupted: yes', 'Actividad interrumpida: sí') : t('Business interrupted: no', 'Actividad interrumpida: no')} onPress={() => setInterrupted(value => !value)} /><Field label={t('Effect on your business', 'Efecto en el negocio')} value={impact} onChange={setImpact} multiline /><Action disabled={task.busy || !requestId || !locationId} label={t('Link request to location', 'Vincular solicitud al local')} onPress={() => void task.run(async () => { await post(`/api/business/organizations/${id}/requests`, token, saved, { requestId, locationId, businessInterruption: interrupted, impactNote: impact }); }, t('Repair linked.', 'Reparación vinculada.'))} /><Text style={styles.muted}>{t('After linking, choose a received quote to request approval.', 'Después de vincular, elige un presupuesto recibido para solicitar autorización.')}</Text>{remote.data?.quotes.filter(item => item.requestId === requestId).map(item => <Action key={item.id} disabled={task.busy} label={`${t('Request approval', 'Solicitar autorización')}: ${item.providerName} · ${dollars(item.amountCents, locale)}`} onPress={() => void task.run(async () => { await post(`/api/business/organizations/${id}/approvals`, token, saved, { quoteId: item.id }); }, t('Approval requested.', 'Autorización solicitada.'))} />)}</Screen>;
}
