import { useRemote, useTask, words } from './state';
import { useState } from 'react';
import { Text, View } from 'react-native';
import { z } from 'zod';
import { parseDateInput } from './formValues';
import { post } from '../platform/api';
import { Action, Check, styles } from '../chat/ui';
import { Field, Screen, Section, type ManagementProps } from './shared';

const maintenance = z.object({ request_id: z.string(), service_address: z.string(), asset_name: z.string(), parts: z.array(z.object({ name: z.string(), quantity: z.number() })), warranty_until: z.string().nullable(), completed_at: z.string() });
const dedicated = z.object({ id: z.string(), provider_id: z.string(), service_address: z.string(), category: z.string(), status: z.enum(['proposed', 'active', 'released']) });
const careSchema = z.object({ bundles: z.array(z.object({ id: z.string(), primary_request_id: z.string(), status: z.string(), service_address: z.string(), care_bundle_items: z.array(z.object({ request_id: z.string() })) })), dedicated: z.array(dedicated), maintenance: z.array(maintenance), reminders: z.array(z.object({ id: z.string(), request_id: z.string(), kind: z.string(), due_at: z.string(), dismissed_at: z.string().nullable() })), priority: z.array(z.object({ request_id: z.string(), status: z.string(), expires_at: z.string() })) });
const requestsSchema = z.object({ requests: z.array(z.object({ id: z.string(), description: z.string(), address: z.string(), status: z.string() })) });
const ok = z.object({ ok: z.boolean() });
export function CareScreen(props: ManagementProps) {
  const { accessToken: token, locale, role } = props; const t = (en: string, es: string) => words(locale, en, es);
  const remote = useRemote('/api/care', token, careSchema, locale); const jobs = useRemote('/api/dashboard', token, requestsSchema, locale); const task = useTask(locale);
  const [selected, setSelected] = useState<string[]>([]); const [editing, setEditing] = useState<z.infer<typeof maintenance> | null>(null);
  const act = (path: string, action: string) => void task.run(async () => { if (path.includes('/dedicated/')) await post(path, token, dedicated, { action }); else await post(path, token, ok, { action }); await remote.reload(); }, t('Saved.', 'Guardado.'));
  if (editing) return <MaintenanceEditor {...props} record={editing} onBack={() => { setEditing(null); void remote.reload(); }} />;
  return <Screen {...props} title={t('Home care', 'Cuidado del hogar')}>
    {remote.feedback}{task.feedback}
    <Section title={t('Your regular professional', 'Tu profesional habitual')}>
      <Text style={styles.muted}>{t('After a completed job, you can choose that professional for future requests at this address. Each job still needs its own quote.', 'Después de un trabajo, puedes elegir al profesional para futuras solicitudes en esta dirección. Cada trabajo necesita su presupuesto.')}</Text>
      {remote.data?.dedicated.length === 0 && <Text style={styles.body}>{t('No completed-job proposals yet.', 'Aún no hay propuestas de trabajos terminados.')}</Text>}
      {remote.data?.dedicated.map(item => <View key={item.id} style={styles.separator}><Text style={styles.body}>{item.service_address} · {item.category}</Text><Text selectable style={styles.muted}>{t('Professional', 'Profesional')}: {item.provider_id}</Text><Text style={styles.body}>{item.status === 'active' ? t('Active', 'Activo') : item.status === 'proposed' ? t('Available to choose', 'Disponible para elegir') : t('Released', 'Finalizado')}</Text>{role === 'customer' && item.status !== 'released' && <Action disabled={task.busy} label={item.status === 'active' ? t('Release professional', 'Dejar de asignar') : t('Choose this professional', 'Elegir este profesional')} onPress={() => act(`/api/care/dedicated/${item.id}`, item.status === 'active' ? 'release' : 'accept')} />}</View>)}
    </Section>
    {role === 'customer' && <Section title={t('Combine small jobs', 'Agrupar trabajos pequeños')}>
      <Text style={styles.muted}>{t('Choose 2–5 confirmed handyman requests at the same address, before any quotes or bookings. Each problem keeps its agreed scope.', 'Elige entre 2 y 5 solicitudes confirmadas de mantenimiento en la misma dirección, antes de recibir presupuestos o reservas. Se conserva el alcance de cada problema.')}</Text>{jobs.feedback}
      {jobs.data?.requests.filter(item => ['intake', 'matched'].includes(item.status)).map(item => <Check key={item.id} label={`${item.description} · ${item.address}`} checked={selected.includes(item.id)} onPress={() => setSelected(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])} disabled={task.busy} />)}
      <Action label={t('Create job bundle', 'Agrupar solicitudes')} disabled={task.busy || selected.length < 2 || selected.length > 5} onPress={() => void task.run(async () => { await post('/api/care/bundles', token, z.object({ id: z.string() }), { requestIds: selected }); setSelected([]); await remote.reload(); }, t('Bundle saved.', 'Solicitudes agrupadas.'))} />
      {remote.data?.bundles.map(item => <View key={item.id} style={styles.separator}><Text style={styles.body}>{item.service_address} · {item.care_bundle_items.length} {t('jobs', 'trabajos')} · {item.status === 'active' ? t('One visit', 'Una visita') : t('Released', 'Separados')}</Text>{item.status === 'active' && <><Text style={styles.muted}>{t('You can separate these jobs before a quote or booking exists.', 'Puedes separar estos trabajos antes de que exista un presupuesto o reserva.')}</Text><Action disabled={task.busy} label={t('Separate bundled jobs', 'Separar trabajos agrupados')} onPress={() => void task.run(async () => { await post(`/api/care/bundles/${item.id}/release`, token, ok, {}); await remote.reload(); }, t('Jobs separated.', 'Trabajos separados.'))} /></>}</View>)}
    </Section>}
    {role === 'provider' && <Section title={t('Priority invitations', 'Invitaciones prioritarias')}>{remote.data?.priority.filter(item => item.status === 'offered').map(item => <View key={item.request_id} style={styles.separator}><Text selectable style={styles.body}>{item.request_id}</Text><Text style={styles.muted}>{t('Respond by', 'Responder antes de')}: {new Date(item.expires_at).toLocaleString(locale)}</Text><Action disabled={task.busy} label={t('Accept invitation to quote', 'Aceptar invitación a presupuestar')} onPress={() => act(`/api/care/priority/${item.request_id}`, 'accept')} /><Action disabled={task.busy} label={t('Decline invitation', 'Rechazar invitación')} onPress={() => act(`/api/care/priority/${item.request_id}`, 'decline')} /></View>)}</Section>}
    <Section title={t('Maintenance records', 'Historial de mantenimiento')}>
      {remote.data?.maintenance.length === 0 && <Text style={styles.body}>{t('Completed work will appear here with its parts and warranty.', 'Los trabajos terminados aparecerán aquí con sus piezas y garantía.')}</Text>}
      {remote.data?.maintenance.map(item => <View key={item.request_id} style={styles.separator}><Text style={styles.heading}>{item.asset_name}</Text><Text style={styles.body}>{item.service_address}</Text><Text style={styles.muted}>{new Date(item.completed_at).toLocaleDateString(locale)}</Text>{item.parts.map((part, index) => <Text key={`${part.name}-${index}`} style={styles.body}>{part.quantity} × {part.name}</Text>)}<Text style={styles.body}>{item.warranty_until ? `${t('Warranty until', 'Garantía hasta')} ${new Date(item.warranty_until).toLocaleDateString(locale)}` : t('No warranty date recorded', 'No se registró fecha de garantía')}</Text>{role === 'provider' && <Action label={t('Record parts and next service', 'Registrar piezas y próxima revisión')} onPress={() => setEditing(item)} />}</View>)}
    </Section>
    <Section title={t('Reminders', 'Recordatorios')}>{remote.data?.reminders.filter(item => !item.dismissed_at).map(item => <View key={item.id} style={styles.separator}><Text style={styles.body}>{item.kind === 'warranty' ? t('Warranty', 'Garantía') : t('Maintenance', 'Mantenimiento')} · {new Date(item.due_at).toLocaleDateString(locale)}</Text>{role === 'customer' && <Action label={t('Dismiss reminder', 'Descartar recordatorio')} disabled={task.busy} onPress={() => act(`/api/care/reminders/${item.id}`, 'dismiss')} />}</View>)}</Section>
  </Screen>;
}
function MaintenanceEditor(props: ManagementProps & { readonly record: z.infer<typeof maintenance> }) {
  const { locale, record, accessToken } = props; const t = (en: string, es: string) => words(locale, en, es); const task = useTask(locale);
  const [asset, setAsset] = useState(record.asset_name); const [parts, setParts] = useState(record.parts); const [next, setNext] = useState('');
  return <Screen {...props} title={t('Record maintenance', 'Registrar mantenimiento')}><Field label={t('Equipment or repaired item', 'Equipo o artículo reparado')} value={asset} onChange={setAsset} />{parts.map((part, index) => <View key={index} style={styles.section}><Field label={t('Part name', 'Nombre de pieza')} value={part.name} onChange={name => setParts(items => items.map((item, i) => i === index ? { ...item, name } : item))} /><Field numeric label={t('Quantity', 'Cantidad')} value={String(part.quantity)} onChange={quantity => setParts(items => items.map((item, i) => i === index ? { ...item, quantity: Number(quantity) } : item))} /><Action label={t('Remove part', 'Quitar pieza')} onPress={() => setParts(items => items.filter((_, i) => i !== index))} /></View>)}<Action label={t('Add part', 'Añadir pieza')} onPress={() => setParts(items => [...items, { name: '', quantity: 1 }])} /><Field label={t('Next service date (optional, YYYY-MM-DD)', 'Próxima revisión (opcional, AAAA-MM-DD)')} value={next} onChange={setNext} />{task.feedback}<Action primary disabled={task.busy || !asset.trim()} label={t('Save maintenance record', 'Guardar mantenimiento')} onPress={() => void task.run(async () => { await post(`/api/care/maintenance/${record.request_id}`, accessToken, maintenance, { assetName: asset, parts, ...(next ? { nextServiceAt: parseDateInput(next) } : {}) }); }, t('Maintenance record saved.', 'Mantenimiento guardado.'))} /></Screen>;
}
